-- InferLog schema.
--
-- Two logical owners share one Postgres instance:
--   * the gateway owns `conversations` + `messages` (synchronous chat state)
--   * the ingestion worker owns `inference_logs` (async telemetry)
--
-- They are kept in one file because it's one database and one deploy unit.
-- `gen_random_uuid()` is core Postgres since v13, so no extension needed.

CREATE TABLE IF NOT EXISTS conversations (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title         TEXT,
    provider      TEXT        NOT NULL,
    model         TEXT        NOT NULL,
    system_prompt TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id   UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role              TEXT NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
    content           TEXT NOT NULL,
    -- 'complete' is the normal case; 'cancelled'/'error' mark partial
    -- assistant turns so the UI can render them honestly on resume.
    status            TEXT NOT NULL DEFAULT 'complete',
    -- links a turn back to its inference log (request_id is the join key).
    request_id        UUID,
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation
    ON messages (conversation_id, created_at);

-- Telemetry. Intentionally NOT foreign-keyed to conversations: logs are an
-- independent stream that must survive even if a conversation row is gone,
-- and the writer (worker) shouldn't fail because the gateway hasn't
-- committed yet. conversation_id is a soft reference for joins.
CREATE TABLE IF NOT EXISTS inference_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- request_id is generated by the SDK and is the idempotency key:
    -- the worker upserts on it, so redelivery from the stream is safe.
    request_id          UUID        NOT NULL UNIQUE,
    conversation_id     UUID,
    service             TEXT        NOT NULL,
    provider            TEXT        NOT NULL,
    model               TEXT        NOT NULL,
    status              TEXT        NOT NULL,
    streamed            BOOLEAN     NOT NULL DEFAULT false,

    started_at          TIMESTAMPTZ NOT NULL,
    completed_at        TIMESTAMPTZ NOT NULL,
    latency_ms          INTEGER     NOT NULL,
    ttft_ms             INTEGER,                -- time to first token (streaming only)

    prompt_tokens       INTEGER,
    completion_tokens   INTEGER,
    total_tokens        INTEGER,
    -- derived by the worker during enrichment
    tokens_per_second   DOUBLE PRECISION,
    estimated_cost_usd  DOUBLE PRECISION,

    error_type          TEXT,
    error_message       TEXT,

    input_preview       TEXT,                   -- PII-redacted by the worker
    output_preview      TEXT,                   -- PII-redacted by the worker
    pii_redaction_count INTEGER     NOT NULL DEFAULT 0,

    sdk_version         TEXT,
    schema_version      INTEGER     NOT NULL DEFAULT 1,
    client_metadata     JSONB       NOT NULL DEFAULT '{}'::jsonb,

    received_at         TIMESTAMPTZ NOT NULL,   -- stamped by the ingestion API
    processed_at        TIMESTAMPTZ NOT NULL DEFAULT now()  -- stamped by the worker
);

-- Dashboards slice by time, then by status/model/provider. These three
-- indexes cover the metric queries in metrics.py.
CREATE INDEX IF NOT EXISTS idx_logs_started_at ON inference_logs (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_logs_status     ON inference_logs (status);
CREATE INDEX IF NOT EXISTS idx_logs_conversation ON inference_logs (conversation_id);
